In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [7]:
an=pd.read_csv("C:/Users/mypc/Downloads/sales_data.csv")

In [8]:
an.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [9]:
an.loc[0:19]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150

In [10]:
an.iloc[0:10]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450
5     1072  2026-01-02  Smartphone  Electronics         4        800
6     1055  2026-01-03  Headphones  Accessories         1        150
7     1020  2026-01-03      Laptop  Electronics         1       1200
8     1082  2026-01-03  Smartphone  Electronics         4        800
9     1085  2026-01-04      Laptop  Electronics         1       1200

In [11]:
an.iloc[0:10,0:5]

   OrderID        Date     Product     Category  Quantity
0     1031  2026-01-01  Smartphone  Electronics         3
1     1100  2026-01-02  Headphones  Accessories         2
2     1028  2026-01-02      Laptop  Electronics         2
3     1089  2026-01-02      Laptop  Electronics         3
4     1023  2026-01-02      Tablet  Electronics         4
5     1072  2026-01-02  Smartphone  Electronics         4
6     1055  2026-01-03  Headphones  Accessories         1
7     1020  2026-01-03      Laptop  Electronics         1
8     1082  2026-01-03  Smartphone  Electronics         4
9     1085  2026-01-04      Laptop  Electronics         1

In [12]:
an[an["Quantity"]>2]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
22     1080  2026-01-08  Headphones  Accessories         3        150
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
55     1050  2026-01-19  Smartphone  Electronics         3        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [13]:
an[an["UnitPrice"]<400]

    OrderID        Date     Product     Category  Quantity  UnitPrice
1      1100  2026-01-02  Headphones  Accessories         2        150
6      1055  2026-01-03  Headphones  Accessories         1        150
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
19     1077  2026-01-07  Headphones  Accessories         2        150
22     1080  2026-01-08  Headphones  Accessories         3        150
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
29     1041  2026-01-10  Headphones  Accessories         2        150
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
32     1013  2026-01-11  Headphones  Accessories         2        150
33     1036  2026-01-12  Headphones  Accessories         3        150
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
45     1075  2026-01-15  Smartwatch  Accessories         4        250
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
54     1011  2026-01-19  Headphones  Accessories         2        150
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
59     1016  2026-01-21  Smartwatch  Accessories         2        250
60     1030  2026-01-21  Smartwatch  Accessories         2        250
61     1008  2026-01-21  Smartwatch  Accessories         1        250
63     1022  2026-01-21  Headphones  Accessories         1        150
64     1059  2026-01-21  Headphones  Accessories         2        150
65     1034  2026-01-22  Headphones  Accessories         1        150
70     1012  2026-01-23  Headphones  Accessories         1        150
77     1070  2026-01-26  Headphones  Accessories         1        150
82     1039  2026-01-27  Smartwatch  Accessories         1        250
85     1065  2026-01-28  Smartwatch  Accessories         1        250
86     1076  2026-01-28  Headphones  Accessories         3        150
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
92     1096  2026-01-29  Smartwatch  Accessories         1        250
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

In [14]:
an[an["OrderID"]<=1003]

    OrderID        Date     Product     Category  Quantity  UnitPrice
20     1001  2026-01-07  Smartphone  Electronics         4        800
57     1002  2026-01-20  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150

In [15]:
an[an["OrderID"]>=1003]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[98 rows x 6 columns]

In [16]:
an[(an["OrderID"]<=1003) & (an["Quantity"]>=2)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
20     1001  2026-01-07  Smartphone  Electronics         4        800
57     1002  2026-01-20  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150

In [17]:
an.sort_values("Quantity")

    OrderID        Date     Product     Category  Quantity  UnitPrice
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
61     1008  2026-01-21  Smartwatch  Accessories         1        250
50     1086  2026-01-18      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
74     1054  2026-01-25  Smartphone  Electronics         4        800
94     1007  2026-01-29  Smartphone  Electronics         4        800
88     1042  2026-01-28      Tablet  Electronics         4        450
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

[100 rows x 6 columns]

In [18]:
an[an["UnitPrice"]!=150]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
..      ...         ...         ...          ...       ...        ...
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[78 rows x 6 columns]

In [19]:
an.sort_values("Quantity",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
4      1023  2026-01-02      Tablet  Electronics         4        450
24     1087  2026-01-08      Laptop  Electronics         4       1200
..      ...         ...         ...          ...       ...        ...
76     1064  2026-01-25      Tablet  Electronics         1        450
85     1065  2026-01-28  Smartwatch  Accessories         1        250
95     1026  2026-01-30      Tablet  Electronics         1        450
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200

[100 rows x 6 columns]

In [20]:
an.sort_values("Quantity",ascending=True)

    OrderID        Date     Product     Category  Quantity  UnitPrice
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
61     1008  2026-01-21  Smartwatch  Accessories         1        250
50     1086  2026-01-18      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
74     1054  2026-01-25  Smartphone  Electronics         4        800
94     1007  2026-01-29  Smartphone  Electronics         4        800
88     1042  2026-01-28      Tablet  Electronics         4        450
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

[100 rows x 6 columns]

In [21]:
an.sort_values(by=["Quantity","Category"],ascending=[True,False])

    OrderID        Date     Product     Category  Quantity  UnitPrice
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
50     1086  2026-01-18      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
45     1075  2026-01-15  Smartwatch  Accessories         4        250
49     1062  2026-01-18  Smartwatch  Accessories         4        250
58     1073  2026-01-20  Smartwatch  Accessories         4        250
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

[100 rows x 6 columns]

In [22]:
print(an.groupby('Quantity')['UnitPrice'].min())

Quantity
1    150
2    150
3    150
4    150
Name: UnitPrice, dtype: int64

In [23]:
print(an.groupby('Quantity')['UnitPrice'].max())

Quantity
1    1200
2    1200
3    1200
4    1200
Name: UnitPrice, dtype: int64

In [24]:
print(an.groupby('Quantity')['UnitPrice'].sum())

Quantity
1    13950
2    12150
3    14300
4    17300
Name: UnitPrice, dtype: int64

In [25]:
print(an.groupby('Quantity')['UnitPrice'].count())

Quantity
1    22
2    21
3    26
4    31
Name: UnitPrice, dtype: int64

In [26]:
print(an.groupby('Quantity')['UnitPrice'].std())

Quantity
1    462.237406
2    446.254252
3    425.910789
4    351.922523
Name: UnitPrice, dtype: float64

In [27]:
an['TotalPrice'] = an['Quantity'] * an['UnitPrice']
print(an)

    OrderID        Date     Product     Category  Quantity  UnitPrice  \
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

    TotalPrice
0         2400
1          300
2         2400
3         3600
4         1800
..         ...
95         450
96         300
97        1000
98        1000
99        1350

[100 rows x 7 columns]

In [28]:
an['Addition'] = an['Quantity'] + an['UnitPrice']
print(an)

    OrderID        Date     Product     Category  Quantity  UnitPrice  \
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

    TotalPrice  Addition
0         2400       803
1          300       152
2         2400      1202
3         3600      1203
4         1800       454
..         ...       ...
95         450       451
96         300       152
97        1000       254
98        1000       254
99        1350       453

[100 rows x 8 columns]