In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [3]:
df=pd.read_csv("C:/Users/mypc/Downloads/spending_patterns_detailed.csv")

In [4]:
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28

In [5]:
df.tail()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04

In [6]:
df.size

90000

In [7]:
df.shape

(10000, 9)

In [8]:
df.columns

Index(['Customer ID', 'Category', 'Item', 'Quantity', 'Price Per Unit',
       'Total Spent', 'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [9]:
df.isnull()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

Customer ID         0
Category            0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dropna(inplace = True)

In [14]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

In [15]:
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28

In [16]:
df.loc[0]
df.loc[0:4]

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28

In [17]:
df.iloc[0:9]

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28
5,CUST_0071,Gifts,Flowers,2,15.87,31.74,Digital Wallet,Mobile App,2024-07-14
6,CUST_0165,Transportation,Car Repair,1,371.29,371.29,Debit Card,Mobile App,2024-03-08
7,CUST_0147,Fitness,Personal Trainer,1,140.59,140.59,Debit Card,Mobile App,2023-01-14
8,CUST_0116,Travel,Plane Ticket,1,1011.41,1011.41,Credit Card,In-store,2023-08-15

In [18]:
df[df["Price Per Unit"] < 2000]
df[df["Price Per Unit"] >= 2000]
df[df["Price Per Unit"] <= 2000]
df[df["Price Per Unit"] == 2000]
df[df["Price Per Unit"] != 2000]

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28
...,...,...,...,...,...,...,...,...,...
9995,CUST_0072,Housing and Utilities,Water Bill,1,69.46,69.46,Debit Card,Online,2023-09-01
9996,CUST_0150,Groceries,Snacks,5,15.54,77.70,Debit Card,In-store,2024-06-27
9997,CUST_0122,Shopping,Electronics,1,732.03,732.03,Debit Card,In-store,2024-03-19
9998,CUST_0133,Transportation,Car Repair,1,107.63,107.63,Debit Card,Mobile App,2024-10-17
9999,CUST_0058,Housing and Utilities,Gas Bill,1,98.79,98.79,Credit Card,Mobile App,2024-08-04

In [19]:
df["new"] = df["Quantity"]*2

In [20]:
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,new
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13,2
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04,4
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16,2
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28,10
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28,6

In [21]:
df.groupby("Category")["Quantity"].mean()

Category
Fitness                  3.037547
Food                     2.965995
Friend Activities        3.069519
Gifts                    2.996198
Groceries                3.016270
Hobbies                  2.883627
Housing and Utilities    1.000000
Medical/Dental           1.000000
Personal Hygiene         3.035156
Shopping                 2.927742
Subscriptions            1.000000
Transportation           1.000000
Travel                   1.000000
Name: Quantity, dtype: float64

In [22]:
 df['Payment Method'].unique()

<StringArray>
['Debit Card', 'Digital Wallet', 'Cash', 'Credit Card']
Length: 4, dtype: str

In [23]:
ab = OrdinalEncoder(categories=[["Debit Card","Digital Wallet","Cash","Credit Card"]])
df["Membership_Level1"]= ab.fit_transform(df[['Payment Method']])
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,new,Membership_Level1
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13,2,0.0
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04,4,0.0
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16,2,1.0
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28,10,2.0
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28,6,0.0

In [24]:
le = LabelEncoder()

In [25]:
df["Item2"] = le.fit_transform(df["Item"])

In [26]:
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,new,Membership_Level1,Item2
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Debit Card,Mobile App,2024-11-13,2,0.0,28
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,Debit Card,In-store,2023-05-04,4,0.0,11
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Digital Wallet,Mobile App,2023-12-16,2,1.0,45
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,Cash,In-store,2024-01-28,10,2.0,47
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,Debit Card,In-store,2023-07-28,6,0.0,16

In [27]:
df=pd.get_dummies(df,columns=["Payment Method"],dtype=int)
df.head()

,Customer ID,Category,Item,Quantity,Price Per Unit,Total Spent,Location,Transaction Date,new,Membership_Level1,Item2,Payment Method_Cash,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_Digital Wallet
0,CUST_0159,Groceries,Milk,1,1.28,1.28,Mobile App,2024-11-13,2,0.0,28,0,0,1,0
1,CUST_0017,Friend Activities,Dinner with Friends,2,74.69,149.39,In-store,2023-05-04,4,0.0,11,0,0,1,0
2,CUST_0094,Housing and Utilities,Water Bill,1,76.06,76.06,Mobile App,2023-12-16,2,1.0,45,0,0,0,1
3,CUST_0162,Fitness,Yoga Class,5,11.24,56.18,In-store,2024-01-28,10,2.0,47,1,0,0,0
4,CUST_0129,Gifts,Flowers,3,43.71,131.12,In-store,2023-07-28,6,0.0,16,0,0,1,0